View role
jeezusplays/IS212-G6T6 pull request #19
Opened 2023-10-10 11:21 UTC by dehou37

## Pull Request Description

BF-03 View Role Details
<Please provide a brief description of the changes and the purpose of this pull request.>
Pull request to merge into main 
## Checklist (Definition of Done)

- [ ] Unit tests passed
- [ ] Code reviewed
- [✓] Acceptance criteria met
- [✓ ] Test cases passed
- [ ] C4 diagram checked
- [ ] Product owner accepted

## Screenshots (if applicable)
![image](https://github.com/jeezusplays/IS212-G6T6/assets/144538254/366e61f2-9fc7-4f9a-9439-40a09767e5df)

2023-10-10 15:24 UTC, jeezusplays requested changes

2023-10-10 15:24 UTC, jeezusplays commented on role-skill-match-app/resources/views/update-role.blade.php
Standardise 1 as part time, 2 as full time. Selected value is correct, if-else checking is wrong

2023-10-10 15:24 UTC, jeezusplays commented on role-skill-match-app/resources/views/view-role.blade.php
Standardise 1 as part time, 2 as full time. Selected value is correct, if-else checking is wrong

2023-10-10 15:28 UTC, hx240 requested changes
View role details changes:
- standardize 1 = part time, 2 = full time for view-roles
-
Navbar changes:
- staff/hr staff/manager dropdown button is not working or functional at all, please fix it
- "View Role Listings" on navbar should redirect to http://localhost:8000/browse-roles/ 
- There should not be 'Create Role Listing' / 'Edit Role Listing' menu items, please put a 'View Applications' placeholder nav-item for now (Can follow browse-roles branch for navbar guidance)

2023-10-10 15:29 UTC, jeezusplays commented on role-skill-match-app/resources/views/update-role.blade.php
Can also resolve conflict issue by accepting main

![image](https://github.com/jeezusplays/IS212-G6T6/assets/68149788/0484cd5f-48a0-4501-bc31-aeb66cdd52fc)

2023-10-11 07:21 UTC, hx240 approved these changes

2023-10-11 07:44 UTC, jeezusplays approved these changes

2023-10-11 07:45 UTC, merged