Standardize nav bar
jeezusplays/IS212-G6T6 pull request #26
Opened 2023-10-21 14:38 UTC by dehou37

## Pull Request Description
Pull request to standardize nav bar, and pass in hr/staff/manager into url. This will be needed for RL 6 (only allow hr/managers to create/edit roles etc)

## Checklist (Definition of Done)

- [ ] Unit tests passed
- [ ] Code reviewed
- [x] Acceptance criteria met
- [x] Test cases passed
- [ ] C4 diagram checked
- [ ] Product owner accepted

## Screenshots (if applicable)
![image](https://github.com/jeezusplays/IS212-G6T6/assets/144538254/cdffeb8a-7e7d-4ed8-9979-6b9c63050555)

## Additional Notes
Ignore the permissions part, not implemented yet. E.g. if you select "staff" role and go to create role listing, will result in error.

2023-10-21 17:26 UTC, jeezusplays approved these changes

2023-10-22 10:19 UTC, hx240 requested changes
Change breaks functionalities of:
- Create role is unable to create role, redirects to localhost:8000/create-role
- Edit listing and View Role Applicants cannot be accessed at all, displays error (Symfony\ Component\ ErrorHandler\ Error\ FatalErrorTrait "Spatie\Permission\Traits\HasRoles" not found)*
- - [HOT-FIX] Requires users/developers to run 'composer require spatie/laravel-permission' before running the application via php artisan serve

2023-10-22 10:51 UTC, dehou37 commented
Just removed the spatie codes that are affecting the issue, lmk if it doesnt work

2023-10-25 15:16 UTC, hx240 approved these changes
All user stories working, except for AR-1 Apply for Roles 
(Note: Existing main branch for AR-1 is also not working, requires hot-fix after this PR)

2023-10-26 02:55 UTC, jeezusplays approved these changes

2023-10-29 08:04 UTC, closed without merging